### ISSUE TITLE
Folder icon should adapt to theme color

### ISSUE THREAD

**Issue by LightTemplar** [aidenlx/alx-folder-note#110]
Could you please make, that color of icon on folders would also adapt to the theme color, as it does in notes like here: https://github.com/aidenlx/obsidian-icon-shortcodes/issues/31?

**Comment by rben01** [comment]
+1. For now, this sort of works in my CSS snippet:

```css
.alx-folder-icons.theme-dark .nav-folder.alx-folder-with-note[data-icon][data-icon-type=svg] > .nav-folder-title > .nav-folder-title-content::before {
    filter: invert(100%);
}
```
