### ISSUE TITLE
Add space or padding after folder icon

### ISSUE THREAD

**Issue by davidolrik** [aidenlx/alx-folder-note#61]
When adding an icon to  a folder there is no padding between the icon and the folder name.

I have this workaround locally:

```css
body.alx-folder-icons .nav-folder.alx-folder-with-note[data-icon]>.nav-folder-title>.nav-folder-title-content:before {
    padding-right: 5px;
}
```
